doctrine:
  orm:
    auto_mapping: true
    mappings:
      SoapService:
        is_bundle: false
        type: attribute
        dirs:
          - "%kernel.project_dir%/src/SoapService/Customer/Infrastructure/Persistence"
          - "%kernel.project_dir%/src/SoapService/Wallet/Infrastructure/Persistence"
        prefix: 'Src\SoapService'
        alias: SoapService
